#!/bin/bash
set -euo pipefail
cd "$(dirname "$0")/../.." 2>/dev/null || true

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_000_baseline --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.6 low_thresh 0.1 iou_thresh 0.15 inertia 0.05 EG_weight_high_score 4.0 EG_weight_low_score 4.4 alpha 0.8 high_score_matching_thresh 0.8 low_score_matching_thresh 0.5 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_001_track050 --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.5 low_thresh 0.1 iou_thresh 0.15 inertia 0.05 EG_weight_high_score 4.0 EG_weight_low_score 4.4 alpha 0.8 high_score_matching_thresh 0.8 low_score_matching_thresh 0.5 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_002_track055 --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.55 low_thresh 0.1 iou_thresh 0.15 inertia 0.05 EG_weight_high_score 4.0 EG_weight_low_score 4.4 alpha 0.8 high_score_matching_thresh 0.8 low_score_matching_thresh 0.5 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_003_track065 --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.65 low_thresh 0.1 iou_thresh 0.15 inertia 0.05 EG_weight_high_score 4.0 EG_weight_low_score 4.4 alpha 0.8 high_score_matching_thresh 0.8 low_score_matching_thresh 0.5 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_004_low005 --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.6 low_thresh 0.05 iou_thresh 0.15 inertia 0.05 EG_weight_high_score 4.0 EG_weight_low_score 4.4 alpha 0.8 high_score_matching_thresh 0.8 low_score_matching_thresh 0.5 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_005_low020 --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.6 low_thresh 0.2 iou_thresh 0.15 inertia 0.05 EG_weight_high_score 4.0 EG_weight_low_score 4.4 alpha 0.8 high_score_matching_thresh 0.8 low_score_matching_thresh 0.5 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_006_iou010 --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.6 low_thresh 0.1 iou_thresh 0.1 inertia 0.05 EG_weight_high_score 4.0 EG_weight_low_score 4.4 alpha 0.8 high_score_matching_thresh 0.8 low_score_matching_thresh 0.5 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_007_iou020 --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.6 low_thresh 0.1 iou_thresh 0.2 inertia 0.05 EG_weight_high_score 4.0 EG_weight_low_score 4.4 alpha 0.8 high_score_matching_thresh 0.8 low_score_matching_thresh 0.5 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_008_inertia002 --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.6 low_thresh 0.1 iou_thresh 0.15 inertia 0.02 EG_weight_high_score 4.0 EG_weight_low_score 4.4 alpha 0.8 high_score_matching_thresh 0.8 low_score_matching_thresh 0.5 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_009_inertia010 --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.6 low_thresh 0.1 iou_thresh 0.15 inertia 0.1 EG_weight_high_score 4.0 EG_weight_low_score 4.4 alpha 0.8 high_score_matching_thresh 0.8 low_score_matching_thresh 0.5 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_010_eg3 --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.6 low_thresh 0.1 iou_thresh 0.15 inertia 0.05 EG_weight_high_score 3.0 EG_weight_low_score 3.4 alpha 0.8 high_score_matching_thresh 0.8 low_score_matching_thresh 0.5 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_011_eg5 --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.6 low_thresh 0.1 iou_thresh 0.15 inertia 0.05 EG_weight_high_score 5.0 EG_weight_low_score 5.4 alpha 0.8 high_score_matching_thresh 0.8 low_score_matching_thresh 0.5 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_012_alpha070 --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.6 low_thresh 0.1 iou_thresh 0.15 inertia 0.05 EG_weight_high_score 4.0 EG_weight_low_score 4.4 alpha 0.7 high_score_matching_thresh 0.8 low_score_matching_thresh 0.5 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_013_alpha090 --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.6 low_thresh 0.1 iou_thresh 0.15 inertia 0.05 EG_weight_high_score 4.0 EG_weight_low_score 4.4 alpha 0.9 high_score_matching_thresh 0.8 low_score_matching_thresh 0.5 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_014_match_loose --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.6 low_thresh 0.1 iou_thresh 0.15 inertia 0.05 EG_weight_high_score 4.0 EG_weight_low_score 4.4 alpha 0.8 high_score_matching_thresh 0.7 low_score_matching_thresh 0.45 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_quick_015_match_strict --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.6 low_thresh 0.1 iou_thresh 0.15 inertia 0.05 EG_weight_high_score 4.0 EG_weight_low_score 4.4 alpha 0.8 high_score_matching_thresh 0.9 low_score_matching_thresh 0.55 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

