#!/bin/bash
set -euo pipefail
# Commands generated by strict sequential HPO runner.
# Run ONE at a time. Do not background these commands.

CUDA_VISIBLE_DEVICES=0,1 /home/ens/Tnehdi/anaconda3/envs/track1/bin/python tools/run_hybrid_sort_dance_jde_parallel.py -f exps/example/dancetrack/yolox_x_dancetrack_jde_v1.py -c YOLOX_outputs/yolox_x_dancetrack_jde_v1_cc_2nodes_8gpu/best_ckpt.pth.tar -b 1 -d 1 --fp16 --fuse --expn hpo_jde_v1_focused_seq_000_tt50_eg3 --parallel-workers 10 --parallel-gpus 0,1 --parallel-clean-results --parallel-progress-mode frames track_thresh 0.5 low_thresh 0.1 iou_thresh 0.15 inertia 0.05 EG_weight_high_score 3.0 EG_weight_low_score 3.4 alpha 0.8 high_score_matching_thresh 0.8 low_score_matching_thresh 0.5 TCM_first_step_weight 1.0 TCM_byte_step_weight 1.0 asso Height_Modulated_IoU

